### ISSUE TITLE
pycricbuzz is broken

### ISSUE THREAD

**Issue by appi147** [codophobia/pycricbuzz#12]
Example link : [http://mapps.cricbuzz.com/cbzios/match/21538/leanback.json](http://mapps.cricbuzz.com/cbzios/match/21538/leanback.json)

There is no `bow_team` as required [in line 99 of cricbuzz.py](https://github.com/codophobia/pycricbuzz/blob/80b31618abfb9d8691a0e45945dee94832164332/pycricbuzz/cricbuzz.py#L99)

which gives error:
```
File "/usr/lib/python3.7/site-packages/pycricbuzz/cricbuzz.py", line 124, in livescore
    d['team'] = bowling['name']
TypeError: 'NoneType' object is not subscriptable

```

**Comment by codophobia** [comment]
@appi147 bow_team is there in that json file.

**Comment by appi147** [comment]
@codophobia Well it was not there in first innings

**Comment by codophobia** [comment]
@appi147 Did this happen before the first ball was bowled? I would suggest you to check match status before calling livescore function.

**Comment by appi147** [comment]
No when India was batting. Exactly when I posted this. I dont have json of that time but lokk for another match.

**Comment by codophobia** [comment]
In case this happens again, take a screenshot of the json file at that moment.

**Comment by appi147** [comment]
Sure

**Comment by kamarajanis** [comment]
yes same issue i faced i just commented because i am not using that variable

**Comment by codophobia** [comment]
@appi147 @kamarajanis I also observed the same bug today. I have fixed it now. You can upgrade to the latest version of pycricbuzz.
