### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by JLashmar** [codophobia/pycricbuzz#13]
The error is located on line 112:

> `d['team'] = team_map[batting.get("id")]`
> AttributeError: 'NoneType' object has no attribute 'get'

**Comment by codophobia** [comment]
https://github.com/codophobia/pycricbuzz/commit/d4dedf799b2b6eabcc99290ef3c8406d31d44889

Fixed. Install the latest version of pycricbuzz and test.
