### ISSUE TITLE
Giving 403 Forbidden from AWS

### ISSUE THREAD

**Issue by piyush2dev** [codophobia/pycricbuzz#18]

**Comment by rakemen** [comment]
Same issue on Heroku. Seems like the cricbuzz cloudflare server is blocking all Heroku and AWS IPs.

**Comment by codophobia** [comment]
I have never tried to use the library from any cloud servers. Cricbuzz servers will block you if you abuse their services.

**Comment by rakemen** [comment]
> 
> 
> I have never tried to use the library from any cloud servers. Cricbuzz servers will block you if you abuse their services.

@codophobia I have never used heroku for deploying a bot that pulls data from Cricbuzz ever, seems like they don't want any scripts pulling data from them from any cloud servers. (AWS, Heroku). Could there be any other way to deploy this apart from just running on the local machine?

**Comment by codophobia** [comment]
https://github.com/codophobia/pycricbuzz/issues/19
