### ISSUE TITLE
Information is not correctly available 

### ISSUE THREAD

**Issue by TeamLazyBuds** [codophobia/pycricbuzz#24]
The timings, status on a match is not correctly available. The match has already started but it shows will start soon.

**Comment by rakemen** [comment]
This issue just started yesterday, until then it was fine, I am not sure what is going wrong and how to connect with the support people on their side. Please comment here if you find any resolution.

**Comment by TeamLazyBuds** [comment]
> This issue just started yesterday, until then it was fine, I am not sure what is going wrong and how to connect with the support people on their side. Please comment here if you find any resolution.

Yeah, same happened yesterday. I also want support on this. And it's really urgent. 😔

**Comment by rakemen** [comment]
@TeamLazyBuds Seems like they fixed it now, the DC RCB match starts as scheduled. Can you confirm?

**Comment by codophobia** [comment]
My code just picks up the information from the cricbuzz API. I am not sure cricbuzz provides any support for this.

**Comment by TeamLazyBuds** [comment]
> @TeamLazyBuds Seems like they fixed it now, the DC RCB match starts as scheduled. Can you confirm?

Yeah, it's working now fetching the latest matches. And as @codophobia said he doesn't have any support for this as it's Cricbuzz api.

**Comment by TeamLazyBuds** [comment]
The issue was resolved. Thank you
