### ISSUE TITLE
API is dead

### ISSUE THREAD

**Issue by virajmane** [codophobia/pycricbuzz#25]
The API has stopped working.
http://mapps.cricbuzz.com/cbzios/match/livematches

**Comment by rakemen** [comment]
Seems like they fixed it now, the DC RCB match starts as scheduled. Can you confirm?

**Comment by codophobia** [comment]
Looks like the API is working now.

**Comment by virajmane** [comment]
I think there are some errors from their side, I can see CSK won in Zimbabwe tour of Pakistan 2020

**Comment by virajmane** [comment]
It's working now
