### ISSUE TITLE
mapps.cricbuzz.com not functional

### ISSUE THREAD

**Issue by rakemen** [codophobia/pycricbuzz#26]
Seems like the [mapps.cricbuzz.com/cbzios/match/livematches](http://mapps.cricbuzz.com/cbzios/match/livematches) site on which this library depends on is not functional now. Anyone facing the same issue?

**Comment by kanishkharde** [comment]
Yes I am facing the same issue. Earlier it used to work fine

**Comment by rakemen** [comment]
Think they have retired the URL or the service. Their bot on Telegram is still pulling scores fine, might be from their private api. @kanishkharde

**Comment by zxw185** [comment]
Hello, has there been any progress made with this?

**Comment by rakemen** [comment]
> Hello, has there been any progress made with this?

No, the cricbuzz score URL is no longer working. So this project is as good as dead for now. You can make use of ESPNCricInfo api url to fetch scores and modify the cricbuzz.py based on this API's response.

Current Matches: https://hs-consumer-api.espncricinfo.com/v1/pages/matches/current?lang=en&latest=true
Live Scorecard: https://hs-consumer-api.espncricinfo.com/v1/pages/match/scorecard?lang=en&seriesId=1263452&matchId=1263462
