### ISSUE TITLE
Blank result

### ISSUE THREAD

**Issue by na-fis** [codophobia/pycricbuzz#9]
This is giving blank result as of now. The reason being that, the xml used for parsing is also empty. Any fixes on that or updated xml link?

**Comment by codophobia** [comment]
I have not found any updated link. Looks like cricbuzz has taken it down.

**Comment by arjun-pp** [comment]
Is there any alternative?

**Comment by Vijayabhaskar96** [comment]
@codophobia https://www.cricbuzz.com/match-api/20211/commentary.json where 20211 is the matchid,
https://www.cricbuzz.com/match-api/livematches.json and https://www.cricbuzz.com/match-api/matches.json for matches. Hope you can update it with these.

**Comment by codophobia** [comment]
@Vijayabhaskar96 Where did you find these links? This looks great. I will update the code and update you.

**Comment by Vijayabhaskar96** [comment]
I found one from Google and others from manually inspecting the website, was about to create a project similar to yours but then I thought it's better if this repository is updated instead of creating a new one (and I don't have time to create and maintain one).

**Comment by codophobia** [comment]
@d1xlord @Vijayabhaskar96 @arjun-pp 
http://mapps.cricbuzz.com/cbzios/match/livematches -  I have updated the code by crawling from this api. Also, I have added some extra fields for matchinfo, commentary, scorecard and livescore.
